# Applies settings on boot
exec-once = python $HOME/.config/casstanje-shell/scripts/applyConfig.py

# Needs a clipboard manager with wl-clipboard support, e.g. cliphist (text + image), clipman (text) or clipse (text and image)
exec-once = wl-paste --type text --watch cliphist store #Stores only text data
exec-once = wl-paste --type image --watch cliphist store #Stores only image data

# wl-clip-persist enables pasting from an application after it exists.
exec-once = wl-clip-persist --clipboard regular

# Starts quickshell and network and bluetooth tray applets 
exec = reloadQs # Start quickshell on boot, restarts it on config reload
exec-once = nm-applet & blueman-applet

# Starts swaybg for wallpapers
exec-once = swaybg -i "$HOME/.config/hypr/assets/plain.png" -m "fill" -o "*"  

# Start hyprpolkitagent
exec-once = systemctl --user start hyprpolkitagent